SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO F
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
     FROM FISH_INFO
     GROUP BY FISH_TYPE) AS MAX_F
ON F.FISH_TYPE = MAX_F.FISH_TYPE AND F.LENGTH = MAX_F.MAX_LENGTH
JOIN FISH_NAME_INFO N
ON F.FISH_TYPE = N.FISH_TYPE
ORDER BY F.ID;